# -*- coding: utf-8 -*-
"""outfit-recommender2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3QcxXsBBEJ2Dh1lAw8uKHi8yqaoyRj9
"""

# Commented out IPython magic to ensure Python compatibility.
# Run this in Colab
!git clone https://github.com/Pavan-02-01/outfit-recommender.git
# %cd outfit-recommender

!mkdir -p data
# Write the CSV file
with open("data/outfits.csv", "w") as f:
  f.write("outfit,color,occasion\n")
  f.write("Casual Shirt and Jeans,Blue,Casual\n")
  f.write("Black Suit,Black,Formal\n")
  f.write("Red Dress,Red,Party\n")
  f.write("Sports Tracksuit,Grey,Sports\n")
# Verify the contents
!cat data/outfits.csv

# Step 4: Create recommender/outfit_recommender.py
# Make sure the recommender directory exists
!mkdir -p recommender
# Create outfit_recommender.py with the recommender class
with open("recommender/outfit_recommender.py", "w") as f:
  f.write("""
import pandas as pd
class OutfitRecommender:
  def __init__(self, csv_path):
    self.data = pd.read_csv(csv_path)
  def recommend(self, color=None, occasion=None):
      result = self.data
      if color:
            result = result[result['color'].str.lower() ==
color.lower()]
      if occasion:
        result = result[result['occasion'].str.lower() ==
occasion.lower()]
        return result['outfit'].tolist()
          """)

# Write the main.py file in the current directory
with open("main.py", "w") as f:
  f.write("""
from recommender.outfit_recommender import OutfitRecommender

def main():
    recommender = OutfitRecommender("data/outfits.csv")
    print("Recommendations for color='Red', occasion='Party':")
    print(recommender.recommend(color='Red', occasion='Party'))

if __name__ == "__main__":
    main()
""")

!python main.py

# Step 7: Use Git in Colab
!git config --global user.email "24msrds040@jainuniversity.ac.in"
!git config --global user.name "Pavan-02-01"

#2. Check Status
!git status

# Commit changes
!git commit -m "Initial recommender version"
#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

!git remote set-url origin https://Pavan-02-01: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@github.com/Pavan-02-01/outfit-recommender.git

#Step 3: Push to GitHub
!git push origin main

with open("requirements.txt", "w") as f:
  f.write("pandas\n")

!cat requirements.txt

pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# STEP 1: Clone the repo and go inside
!git clone https://github.com/Pavan-02-01/outfit-recommender.git
# %cd outfit-recommender

# STEP 2: Make your file changes
!mkdir -p data recommender

with open("data/outfits.csv", "w") as f:
    f.write("outfit,color,occasion\n")
    f.write("Casual Shirt and Jeans,Blue,Casual\n")
    f.write("Black Suit,Black,Formal\n")
    f.write("Red Dress,Red,Party\n")
    f.write("Sports Tracksuit,Grey,Sports\n")

with open("recommender/outfit_recommender.py", "w") as f:
    f.write("""
import pandas as pd

class OutfitRecommender:
    def __init__(self, csv_path):
        self.data = pd.read_csv(csv_path)

    def recommend(self, color=None, occasion=None):
        result = self.data
        if color:
            result = result[result['color'].str.lower() == color.lower()]
        if occasion:
            result = result[result['occasion'].str.lower() == occasion.lower()]
        return result['outfit'].tolist()
""")

with open("main.py", "w") as f:
    f.write("""
from recommender.outfit_recommender import OutfitRecommender

def main():
    recommender = OutfitRecommender("data/outfits.csv")
    print("Recommendations for color='Red', occasion='Party':")
    print(recommender.recommend(color='Red', occasion='Party'))

if __name__ == "__main__":
    main()
""")

with open("requirements.txt", "w") as f:
    f.write("pandas\n")

# STEP 3: Run your main script
!python main.py

# Set your Git identity (only needed once per Colab session)
!git config --global user.email "24msrds040@jainuniversity.ac.in"
!git config --global user.name "Pavan-02-01"

# Add all files
!git add .

# Commit the changes
!git commit -m "Added outfit recommender script and data"

# Push using Personal Access Token (PAT) securely
# Replace YOUR_TOKEN_HERE with your actual GitHub PAT
!git remote set-url origin https://Pavan-02-01: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@github.com/Pavan-02-01/outfit-recommender.git
!git push origin main